### ISSUE TITLE
I can't connect VPN on Fedora 40

### ISSUE THREAD

**Issue by khaerunsituncu** [ruyrybeyro/chrootvpn#33]
![image](https://github.com/ruyrybeyro/chrootvpn/assets/28919882/79e0e511-00b8-41e0-8f62-0b39262b1d37)

Is there a solution to a problem like this?

**Comment by ruyrybeyro** [comment]
I have fixed a X11 authorization issue. Please download it, uninstall and install again as:

    rm vpn.sh
    wget https://raw.githubusercontent.com/ruyrybeyro/chrootvpn/main/vpn.sh
    chmod a+rx vpn.sh
    ./vpn.sh -i --vpn=your_vpn_fqdn
.

**Comment by khaerunsituncu** [comment]
yes, it looks like it has been successful, it has reached the Trust server stage but it still can't connect because of the previous problem

![image](https://github.com/ruyrybeyro/chrootvpn/assets/28919882/ede462a4-6350-4733-aaa1-419fafe00eb2)

**Comment by ruyrybeyro** [comment]
Please visit https://localhost:14186/id and accept the certificate, if necessary. This step may not be required for Fedora 40 with Firefox. I do not believe this is the issue though. 

Unfortunately, I cannot provide further assistance. This issue appears to be server-related and should be addressed by your local networking team or help desk.

**Comment by khaerunsituncu** [comment]
but on the Windows VPN client it can connect, Is it restricted on Linux?

**Comment by ruyrybeyro** [comment]
The Windows VPN client is using a slightly different method, not the web portal.
